Dashboard/QCEO_Django/QCEO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('extern.urls', namespace='surface')),
	path('functionauto/', include('functionauto.urls', namespace='functionauto')),
	path('analysis/', include('analysis.urls', namespace='analysis')),
	path('logperform/', include('logperform.urls', namespace='logperform')),
	path('logmonitor/', include('logmonitor.urls', namespace='logmonitor')),
	path('qualityauto/', include('qualityauto.urls', namespace='qualityauto')),
    
    path("api/",include('Accounts.urls')),
    path('api/auth/', include('knox.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashboard/QCEO_Django/logperform/urls.py
from django.urls import path
from . import views

app_name = 'logperform'

urlpatterns =[
	path('', views.logperform, name='logperform'),
	path('ajax/', views.performdata, name='performdata'),
	path('delete/', views.agentdelete, name='agentdelete'),
	path('datadelete/', views.performdatadelete, name='performdatadelete'),
]

Dashboard/QCEO_Django/logperform/models.py
from django.db import models

# Create your models here.
class Logagent(models.Model):
	product = models.CharField('제품명', max_length=30)
	version = models.CharField('버전', max_length=30)
	logpath = models.CharField('로그경로', max_length=50)

class Loglist(models.Model):
	product = models.CharField('제품명', max_length=30)
	version = models.CharField('버전', max_length=30)
	whitelist = models.TextField('허용문구', blank=True)
	blacklist = models.TextField('비허용문구', blank=True)
	
class Performance(models.Model):
	timestamp = models.DateTimeField('시간', null=True, blank=True)
	agent = models.CharField('에이전트', max_length=30, blank=True)
	cpu = models.CharField('전체CPU사용량', max_length=30, blank=True)
	memory = models.CharField('전체메모리사용량', max_length=30, blank=True)
	p1cpu = models.CharField('p1CPU사용량', max_length=30, blank=True)
	p1memory = models.CharField('p1메모리사용량', max_length=30, blank=True)
	p2cpu = models.CharField('p2CPU사용량', max_length=30, blank=True)
	p2memory = models.CharField('p2메모리사용량', max_length=30, blank=True)
	p3cpu = models.CharField('p3CPU사용량', max_length=30, blank=True)
	p3memory = models.CharField('p3메모리사용량', max_length=30, blank=True)
	p4cpu = models.CharField('p4CPU사용량', max_length=30, blank=True)
	p4memory = models.CharField('p4메모리사용량', max_length=30, blank=True)
	p5cpu = models.CharField('p5CPU사용량', max_length=30, blank=True)
	p5memory = models.CharField('p5메모리사용량', max_length=30, blank=True)

class Performagent(models.Model):
	ostype = models.CharField('OS', max_length=20, blank=True)
	process1 = models.CharField('프로세스1', max_length=20, blank=True)
	process2 = models.CharField('프로세스2', max_length=20, blank=True)
	process3 = models.CharField('프로세스3', max_length=20, blank=True)
	process4 = models.CharField('프로세스4', max_length=20, blank=True)
	process5 = models.CharField('프로세스5', max_length=20, blank=True)

Dashboard/QCEO_Django/logperform/forms.py
from django import forms
from django.forms import ModelForm
from .models import Performagent

class ReserveForm(forms.ModelForm):
	class Meta:
		model = Performagent
		fields = ['ostype', 'process1', 'process2', 'process3', 'process4', 'process5']

Dashboard/QCEO_Django/logperform/views.py
import os
import sys
import json
import datetime
from time import mktime
from django.core.serializers.json import DjangoJSONEncoder
from django.core.files import File
from django.shortcuts import render
from django.http import HttpResponse
from .models import Performance, Performagent
from .forms import ReserveForm

# Create your views here.
def logperform(request) :
	if request.method == 'POST':
		form = ReserveForm(request.POST)
		if form.is_valid():
			Performagent(
				ostype=request.POST['ostype'],
				process1=request.POST['process1'],
				process2=request.POST['process2'],
				process3=request.POST['process3'],
				process4=request.POST['process4'],
			).save()
	else:
		form = ReserveForm()

	agentdata = [{'timestamp':mktime(data.timestamp.timetuple()), 'agent':data.agent, 'cpus':[data.cpu, data.p1cpu, data.p2cpu, data.p3cpu, data.p4cpu, data.p5cpu], 'mems':[data.memory, data.p1memory, data.p2memory, data.p3memory, data.p4memory, data.p5memory]} for data in Performance.objects.all()]
	agents = [{'agentname':data['ostype'], 'process1':data['process1'], 'process2':data['process2'], 'process3':data['process3'], 'process4':data['process4']} for data in Performagent.objects.values('ostype', 'process1', 'process2', 'process3', 'process4', 'process5' )]
	
	return render(request, 'logperform/logperform.html', {'agentdata':agentdata, 'form':form, 'agents':agents})


def performdata(request):

	agentdata = [{'timestamp':mktime(data.timestamp.timetuple()), 'agent':data.agent, 'cpus':[data.cpu, data.p1cpu, data.p2cpu, data.p3cpu, data.p4cpu, data.p5cpu], 'mems':[data.memory, data.p1memory, data.p2memory, data.p3memory, data.p4memory, data.p5memory]} for data in Performance.objects.all()]

	return HttpResponse(json.dumps({'agentdata':agentdata}), content_type='application/json')


def agentdelete(request):
	delobj = Performagent.objects.get(ostype=request.POST['ostype'])
	delobj.delete()
	return render(request, 'logperform/agentdelete.html', {})


def performdatadelete(request):
	Performance.objects.all().delete()
	return render(request, 'logperform/performdatadelete.html', {})

Dashboard/QCEO_Django/logperform/templates/logperform/agentdelete.html
<script>
	window.alert('delete complete');
	window.location.href='/logperform/';
</script>

Dashboard/QCEO_Django/logperform/templates/logperform/logperform.html
{% extends "extern/base.html" %}

{% block exterstyle %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static './css/jquery.jqplot.css' %}" />
	<script type="text/javascript" src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
	<script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script type="text/javascript">
	window.onload = function() {
		var act;
		$(function () {
			$(".tab_content").hide();
			$(".tab_content:first").show();
			$("ul.tabs li:first").addClass("active")
			act = $("ul.tabs li.active").html();
			$("ul.tabs li").click(function () {
				$("ul.tabs li").removeClass("active").css("color", "#333");
				//$(this).addClass("active").css({"color": "darkred","font-weight": "bolder"});
				$(this).addClass("active").css("color", "darkred");
				act = $("ul.tabs li.active").html();
				$(".tab_content").hide()
				var activeTab = $(this).attr("rel");
				$("#" + activeTab).fadeIn()
			});
		});
		var agents = [{% for agent in agents %}"{{agent.agentname}}",{% endfor %}];
		function makegraph (agt){
			$(function () {
				var dataPointsCPUs = [[],[],[],[],[],[]];
				var dataPointsMemorys = [[],[],[],[],[],[]];
				var chart1;
				var firstlength;
				var title;
				$.getJSON("{% url 'logperform:performdata' %}", function(data) {  
					$.each(data, function(key, value){
						firstlength = value.length;
						title = agt;
						for(var i=0; i<value.length; i++) {
							if (agt == value[i]['agent']) {
								var timestamp = (value[i]['timestamp']+32400) * 1000
								var date = new Date(timestamp);
								for(var j=0; j<6; j++) {
									dataPointsCPUs[j].push({x: date, y: Number(value[i]['cpus'][j])});
									dataPointsMemorys[j].push({x: date, y: Number(value[i]['mems'][j])});
								}
							}
						}
					});
					var render1 = agt + "cpuchart";
					chart1 = new CanvasJS.Chart(render1,{
						zoomEnabled: true,
						toolTip: {
							shared: true
						},
						axisY: {
							title: "CPU",
							suffix : " %",
							tickColor: "#4F81BC"
						},
						data: [{
							type: "line",
							xValueType: "dateTime",
							name: "CPU",
							dataPoints : dataPointsCPUs[0],
						}, {
							type: "line",
							xValueType: "dateTime",
							name: "P1CPU",
							dataPoints : dataPointsCPUs[1],
						}, {
							type: "line",
							xValueType: "dateTime",
							name: "P2CPU",
							dataPoints : dataPointsCPUs[2],
						}, {
							type: "line",
							xValueType: "dateTime",
							name: "P3CPU",
							dataPoints : dataPointsCPUs[3],
						}, {
							type: "line",
							xValueType: "dateTime",
							name: "P4CPU",
							dataPoints : dataPointsCPUs[4],
						}, {
							type: "line",
							xValueType: "dateTime",
							name: "P5CPU",
							dataPoints : dataPointsCPUs[5],
						}]
					});
					chart1.render();
					var render2 = agt + "memchart";
					chart2 = new CanvasJS.Chart(render2,{
						zoomEnabled: true,
						toolTip: {
							shared: true
						},
						axisY: {
							title: "Memory",
							suffix : " %",
							tickColor: "#4F81BC"
						},
						data: [{
							type: "line",
							xValueType: "dateTime",
							name: "Memory",
							dataPoints : dataPointsMemorys[0],
						}, {
							type: "line",
							xValueType: "dateTime",
							name: "P1Memory",
							dataPoints : dataPointsMemorys[1],
						}, {
							type: "line",
							xValueType: "dateTime",
							name: "P2Memory",
							dataPoints : dataPointsMemorys[2],
						}, {
							type: "line",
							xValueType: "dateTime",
							name: "P3Memory",
							dataPoints : dataPointsMemorys[3],
						}, {
							type: "line",
							xValueType: "dateTime",
							name: "P4Memory",
							dataPoints : dataPointsMemorys[4],
						}, {
							type: "line",
							xValueType: "dateTime",
							name: "P5Memory",
							dataPoints : dataPointsMemorys[5],
						}]
					});
					chart2.render();
					updateChart();
				});

				function updateChart() {
					$.getJSON("http://192.168.120.166:8000/logperform/ajax", function(data) {
						$.each(data, function(key, value) {
							for(var i=firstlength; i<value.length; i++) {
								if (agt == value[i]['agent']) {
									var timestamp = (value[i]['timestamp']+32400) * 1000
									var date = new Date(timestamp);
									for(var j=0; j<6; j++) {
										dataPointsCPUs[j].push({x: date, y: Number(value[i]['cpus'][j])});
										dataPointsMemorys[j].push({x: date, y: Number(value[i]['mems'][j])});
									}
								}
								firstlength = value.length;
							}
							});
						chart1.render();
						chart2.render();
						setTimeout(function(){updateChart()}, 5000);
					});
				}
			});
		}
		for (var i=0; i<agents.length; i++)	makegraph(agents[i]);
	}
	</script>


{% endblock exterstyle %}

{% block content %}
<h1>성능 모니터링</h1>
<div class="contents">
	<h2>CPU/Memory 모니터링</h2>
	<a href="datadelete/">데이터 삭제하기</a>
	<ul class="tabs">
		{% for agent in agents %}
		<li rel="tab{{ forloop.counter }}">{{ agent.agentname }}</li>
		{% endfor %}
    </ul>
	<div class="tab_container">
		{% for agent in agents %}
		<div id="tab{{ forloop.counter }}" class="tab_content">
			<h3>CPU</h3>
			<div id="{{ agent.agentname }}cpuchart" style="height: 300px; width: 100%;"></div>
			<h3>Memory</h3>
			<div id="{{ agent.agentname }}memchart" style="height: 300px; width: 100%;"></div>
		</div>
		{% endfor %}
	</div>
</div>
<div class="contents">
	<h2>에이전트 관리</h2>
	<ul>
		<li><a href="/report/agents/aixagent">aixagent 다운로드</a></li>
		<li><a href="/report/agents/linuxagent">linuxagent 다운로드</a></li>
		<li><a href="/report/agents/solarisagent">solarisagent(11) 다운로드</a></li>
	</ul>
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_table}}
		<input type="submit" value="생성">
	</form>
		<table class="agents">
			<tr>
				<th>운영체제 이름</th>
				<th>프로세스</th>
				<th>삭제</th>
			</tr>
			{% for agent in agents %}
			<form action="delete/" method="post">
				<tr>		
					{% csrf_token %}
					<td>{{agent.agentname}}</td>
					<td>{{agent.process1}} {{agent.process2}} {{agent.process3}} {{agent.process4}} {{agent.process4}}</td>
					<td><input type="hidden" name="ostype" value="{{agent.agentname}}"><input type="submit" value="삭제"></td>
				</tr>
			</form>
			{% endfor %}
		</table>
</div>
{% endblock content %}

Dashboard/QCEO_Django/logperform/templates/logperform/performdatadelete.html
<script>
	window.alert('delete complete');
	window.location.href='/logperform/';
</script>