Dashboard/QCEO_Django/QCEO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('extern.urls', namespace='surface')),
	path('functionauto/', include('functionauto.urls', namespace='functionauto')),
	path('analysis/', include('analysis.urls', namespace='analysis')),
	path('logperform/', include('logperform.urls', namespace='logperform')),
	path('logmonitor/', include('logmonitor.urls', namespace='logmonitor')),
	path('qualityauto/', include('qualityauto.urls', namespace='qualityauto')),
    
    path("api/",include('Accounts.urls')),
    path('api/auth/', include('knox.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashboard/QCEO_Django/functionauto/urls.py
from django.urls import path
from . import views

app_name = 'functionauto'

urlpatterns =[
	path('', views.functionauto, name='functionauto'),
	path('ajax/', views.processbars, name='processbars'),
	path('noreport/', views.noreport, name='noreport'),
]

Dashboard/QCEO_Django/functionauto/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Autotest(models.Model):
	PATHS = (
		('/home/qceo/windowshare/Linux', 'Linux'),
		('/home/qceo/windowshare/Solaris_intel', 'Solaris'),
		('/home/qceo/windowshare/UNIX', 'UNIX'),
	)
	project = models.CharField('프로젝트', max_length=30)
	testname = models.CharField('테스트명', max_length=30)
	total = models.IntegerField('전체폴더개수')
	starttime = models.DateTimeField('테스트시간')
	path = models.CharField('경로', max_length=100, choices=PATHS, blank=True)
	file = models.FileField('보고서', blank=True)
	is_deleted = models.BooleanField('등록', default=True)
	
class Testreserve(models.Model):
	STATES = (
		('예약', '예약'),
		('접수', '접수'),
		('진행', '진행'),
		('완료', '완료'),
	)
	name = models.CharField('예약자명', max_length=30)
	reservetime = models.DateTimeField('예약시간', default=timezone.now)
	starttime = models.DateTimeField('희망시작시간', default=timezone.now)
	project = models.CharField('프로젝트명', max_length=30)
	memo = models.TextField('메모', blank=True)
	state = models.CharField('상태', max_length=2, choices=STATES, default='예약')
	is_deleted = models.BooleanField('등록', default=True)

Dashboard/QCEO_Django/functionauto/forms.py
from django import forms
from django.forms import ModelForm
from .models import Testreserve
from django.forms.fields import DateTimeField

class ReserveForm(forms.ModelForm):
	class Meta:
		model = Testreserve
		fields = ['name', 'project', 'memo', 'starttime']

Dashboard/QCEO_Django/functionauto/views.py
import json
import os
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from functionauto.models import Autotest, Testreserve
from .forms import ReserveForm

# Create your views here.

@login_required
def functionauto(request):
	form = ReserveForm()
	if 'reserve' in request.POST:
		form = ReserveForm(request.POST)
		if form.is_valid():
			form.save()
			form = ReserveForm()

	elif 'mount' in request.POST:
		os.system('sudo mount -a')

	datas = []
	num = 0
	testsets = Autotest.objects.values("project", "testname", "total",	"starttime", "path", "file")
	totalnum = Autotest.objects.all().count()
	for testset in testsets:
		if testset['path']:
			dirpath = testset['path']
			dirs = []
			for filename in os.listdir(dirpath):
				full_filename = os.path.join(dirpath, filename)
				if os.path.isdir(full_filename):
					dirs.append(filename)
			if len(dirs) != 0:
				dirlen = round(testset['total']/len(dirs)) * 100
			else:
				dirlen = 0
			datas.append({"num":str(num), "project":testset["project"], "testname":testset["testname"], "total":testset["total"], "starttime":testset["starttime"], "dirlen":dirlen, "file":testset["file"]})
			num = num + 1

	reserves = Testreserve.objects.values("project", "name", "state", "starttime", "reservetime")
		
	return render(request, 'functionauto/functionauto.html', {'datas':datas, 'totalnum':totalnum, 'form':form, 'reserves':reserves})


@login_required
def processbars(request):
	datas = []
	num = 0
	testsets = Autotest.objects.values("project", "testname", "total",	"starttime", "path")
	totalnum = Autotest.objects.all().count()
	for testset in testsets:
		dirpath = testset['path']
		dirs = []
		for filename in os.listdir(dirpath):
			full_filename = os.path.join(dirpath, filename)
			if os.path.isdir(full_filename):
				dirs.append(filename)
		dirlen = len(dirs)
		datas.append({"num":str(num), "project":testset["project"], "testname":testset["testname"], "total":str(testset["total"]), "starttime":str(testset["starttime"]), "dirlen":dirlen})
		num = num + 1
	return HttpResponse(json.dumps({'datas':datas, 'totalnum':totalnum}), content_type='application/json')


def noreport(request):
	print("test")
	return render(request, 'functionauto/noreport.html', {'return':0})

Dashboard/QCEO_Django/functionauto/templates/functionauto/functionauto.html
{% extends "extern/base.html" %}

{% block exterstyle %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		//$("#id_starttime").val("0000-00-00 00:00:00");
		$(".UpdateTest").click(function(){
			$.ajax({
				type: "POST",
				url: "{% url 'functionauto:processbars' %}",
				data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
				dataType: "json", 
				success: function(response){
					{% for test in datas %}
						$(".autotest{{test.num}} .testing_bar").css('width', Math.floor(response.datas[{{ test.num }}].dirlen/{{ test.total }}*100) + "%");
						$(".autotest{{test.num}} .testing_bar").html(Math.floor(response.datas[{{ test.num }}].dirlen/{{ test.total }}*100) + "%");
					{% endfor %}
				},
				error:function(request,status,error){
					console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
				}
			});
		})
	})
</script>
{% endblock exterstyle %}

{% block content %}
	<h1>기능자동화</h1>
	<div class="contents">
		<h2>자동테스트 예약</h2>
		<form action="" method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" name="reserve" value="예약">
		</form>
	</div>
	<div class="contents">
		<h2>예약자 현황</h2>
		<table class="reserve">
			<colgroup>
				<col style="width:20%">
				<col style="width:10%">
				<col style="width:10%">
				<col style="width:30%">
				<col style="width:30%">
			</colgroup>
			<thead>
				<tr>
					<th>프로젝트</th>
					<th>예약자</th>
					<th>상태</th>
					<th>희망 테스트 시간</th>
					<th>예약 등록 시간</th>
				</tr>
			</thead>
			<tbody>
			{% for reserve in reserves %}
				<tr>
					<td>{{ reserve.project }}</td>
					<td>{{ reserve.name }}</td>
					<td>{{ reserve.state }}</td>
					<td>{{ reserve.starttime|date:"m/d h:s" }}</td>
					<td>{{ reserve.reservetime|date:"m/d h:s" }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="contents">
		<h2>자동테스트 알림</h2>
		<form method="post" class="sharemount">
			{% csrf_token %}
			<input type="submit" name="mount" value="공유폴더 마운트">
		</form>
		<input type="button" class="UpdateTest" value="현재 상황 새로고침">
		{% for test in datas %}
			<div class="autotest{{test.num}} autotest">
				<h3 class="project">{{ test.project }}</h3>
				<div class="project_info">
					<span class="testname"><b>테스트명</b> {{ test.testname }}</span>
					<span class="starttime"><b>테스트 시작시간</b> {{ test.starttime }}</span>
					<span class="project_repoart"><a href="{% if test.file %}/report/{{ test.file }} {% else %} {% url 'functionauto:noreport' %}  {% endif %}">자동테스트 결과</a></span>
				</div>
				<div class="testing_bar" style="width:{{ test.dirlen }}%;"></div>
			</div>
		{% endfor %}
	</div>	
	
{% endblock content %}
	

Dashboard/QCEO_Django/functionauto/templates/functionauto/noreport.html
<script>
	console.log(typeof({{ return }}))
	if ({{ return }} == "0")
	{
		window.alert('결과 리포트가 없습니다');
		window.location.href='{% url 'functionauto:functionauto' %}';
	}
</script>

<h1> {{ return }} </h1>