Dashboard/QCEO_Django/QCEO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('extern.urls', namespace='surface')),
	path('functionauto/', include('functionauto.urls', namespace='functionauto')),
	path('analysis/', include('analysis.urls', namespace='analysis')),
	path('logperform/', include('logperform.urls', namespace='logperform')),
	path('logmonitor/', include('logmonitor.urls', namespace='logmonitor')),
	path('qualityauto/', include('qualityauto.urls', namespace='qualityauto')),
    
    path("api/",include('Accounts.urls')),
    path('api/auth/', include('knox.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashboard/QCEO_Django/extern/urls.py
from django.urls import path
#from django.contrib.auth.views import login, logout
from django.contrib.auth import views as auth_views
from . import views

app_name = 'extern'

urlpatterns =[
	#path('', login, {'template_name': 'extern/login.html'}, name='index'),
	path('', auth_views.LoginView.as_view(template_name='extern/login.html'), name='index'),
	path('dashboard/', views.dashboard, name='dashboard'),
	path('product/<int:product_id>', views.product, name='product'),
	#path('logout/', logout, {'template_name': 'extern/logout.html'}, name='logout'),
	path('logout/', auth_views.LoginView.as_view(template_name='extern/logout.html'), name='logout'),
	path('dashboard/sendmail', views.sendmail, name='sendmail'),
	path('product/<int:product_id>/sendmail', views.productsendmail, name='productsendmail'),
]

Dashboard/QCEO_Django/extern/models.py
from django.db import models

# Create your models here.
class additional(models.Model):
	goal = models.IntegerField('목표매출', null=True, blank=True)
	currnet = models.IntegerField('현재매출', null=True, blank=True)
	motto = models.CharField('좌우명', max_length=30)

Dashboard/QCEO_Django/extern/views.py
from datetime import date, timedelta, datetime
import datetime
import re
import math
import numpy as np
import smtplib
from email.mime.text import MIMEText
from django.shortcuts import render
from dataproc.models import Data, Process, Company, Totalquality, Productquality
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.db.models import Count

# Create your views here.
@login_required
def dashboard(request):
	days = [date.today() - timedelta(x) for x in range(4, -1, -1)]
		
	# 전체품질 : 날짜 입력되지 않았을 경우 - 5일치, 날짜 입력 받아서 지정기간 품질 출력
	sdate = days[0].strftime("%Y-%m-%d") # 기본 시작날짜 - 5일전
	edate = days[4].strftime("%Y-%m-%d") # 기본 끝날짜 - 오늘



	if request.POST: # 입력된 날짜대로 지정 기간설정
		sdate = request.POST.get('sdate')
		edate = request.POST.get('edate')
	# 설정된 기간만큼 전체품질 현황 출력
	termset = Totalquality.objects.filter(date__range=(sdate, edate)).values('manualtest', 'process', 'faulty', 'date').order_by('date') #설정된 기간만큼 manualtest(수동테스트), process(프로세스), faulity(결함율)을 가져옴
	qualities = [{'date':term['date'].strftime("%m/%d"), 'value':term['manualtest'] + term['process'] + term['faulty']} for term in termset] # 날짜와 가져온 값들을 더해서 리스트로 묶음
		
	#등록된 프로젝트 프로레스 출력
	processbars = []
	project_set = Process.objects.values('project','version', 'start', 'end', 'firststep', 'secondstep', 'thirdstep', 'file', 'is_deleted') # 프로젝트 관련정보 가져오기
	for project in project_set:
		totaldays = int(re.findall('\d+', str(project['end']-project['start']))[0]) # 전체기간 계산
		fstepdays = int(re.findall('\d+', str(project['firststep']-project['start']))[0]) # 개발 기간 계산
		sstepdays = int(re.findall('\d+', str(project['secondstep']-project['firststep']))[0]) # 품질점검 기간 계산
		tstepdays = int(re.findall('\d+', str(project['thirdstep']-project['secondstep']))[0]) # 패키징 기간 계산
		estepdays = int(re.findall('\d+', str(project['end']-project['thirdstep']))[0]) # 설치 기간 계산
		currentdays = int(re.findall('\d+', str(date.today()-project['start']))[0]) # 시작일부터 현재까지 지난 기간 계산
		
		nowper = str(round((currentdays / totaldays) * 100)) # 전체기간중 지난 기간 비율로 환산
		if int(nowper) > 100: nowper = '100' # 100퍼센트가 넘어가면 100퍼센트로 고정
		fdays = str(math.floor((fstepdays / totaldays) * 100)) # 개발기간 비율 계산
		sdays = str(math.floor((sstepdays / totaldays) * 100)) # 품질점검 기간 비율 계산
		tdays = str(math.floor((tstepdays / totaldays) * 100)) # 패키징 기간 비율 계산
		edays = str(math.floor((estepdays / totaldays) * 100)) # 설치 기간 비율 계산

		processbars.append({
			'project':project['project'], # 프로젝트 명
			'version':project['version'], # 버전 정보
			'firststep':project['firststep'], # 개발기간 비율
			'secondstep':project['secondstep'], # 품질점검 기간 비율
			'thirdstep':project['thirdstep'], # 패키징 기간 비율
			'end':project['end'], # 설치 기간 비율
			'fdays':fdays, # 개발 시작 날짜
			'sdays':sdays, # 품질점검 시작 날짜
			'tdays':tdays, # 패키징 시작 날짜
			'edays':edays, # 설치 시작 날짜
			'nowper':nowper, # 오늘까지 지난 날들의 전체 퍼센트
			'file':project['file'], # 업로드한 보고서
			'is_deleted':project['is_deleted'], # 등록/등록해제
		})
	

	defectsdate = datetime.datetime.strptime(sdate, "%Y-%m-%d")
	defectedate = datetime.datetime.strptime(edate, "%Y-%m-%d")
	totalterm = int((defectedate-defectsdate).days)
	print(totalterm)

	#전체 결함 및 제품별 결함 출력
	data = [{'value':str(Data.objects.filter(inputdate__icontains=(defectsdate+datetime.timedelta(days=x)).strftime("%m-%d")).count()), 'date': str((defectsdate+datetime.timedelta(days=x)).strftime("%m-%d"))} for x in range(0, totalterm+1)] # 전체결함 출력
	p1 = [{'value':str(Data.objects.filter(project__icontains='SecuMS', inputdate__icontains=(defectsdate+datetime.timedelta(days=x)).strftime("%m-%d")).count()), 'date': str((defectsdate+datetime.timedelta(days=x)).strftime("%m-%d"))} for x in range(0, totalterm+1)] # SecuMS 결함 출력
	p2 = [{'value':str(Data.objects.filter(project__icontains='UniTy UNIX', inputdate__icontains=(defectsdate+datetime.timedelta(days=x)).strftime("%m-%d")).count()), 'date': str((defectsdate+datetime.timedelta(days=x)).strftime("%m-%d"))} for x in range(0, totalterm+1)] # OmniGuard Unix 결함 출력	
	p3 = [{'value':str(Data.objects.filter(project__icontains='UAC for Windows(SE)', inputdate__icontains=(defectsdate+datetime.timedelta(days=x)).strftime("%m-%d")).count()), 'date': str((defectsdate+datetime.timedelta(days=x)).strftime("%m-%d"))} for x in range(0, totalterm+1)] # OmniGuard windows 결함 출력
	p4 = [{'value':str(Data.objects.filter(project__icontains='FOSSGuard', inputdate__icontains=(defectsdate+datetime.timedelta(days=x)).strftime("%m-%d")).count()), 'date': str((defectsdate+datetime.timedelta(days=x)).strftime("%m-%d"))} for x in range(0, totalterm+1)] # FOSSGuard 결함 출력
	p5 = [{'value':str(Data.objects.filter(project__icontains='Athena Dev', inputdate__icontains=(defectsdate+datetime.timedelta(days=x)).strftime("%m-%d")).count()), 'date': str((defectsdate+datetime.timedelta(days=x)).strftime("%m-%d"))} for x in range(0, totalterm+1)] # Athena Dev 결함 출력

	return render(request, 'extern/dashboard.html', {'datas':data, 'p1s':p1, 'p2s':p2, 'p3s':p3, 'p4s':p4, 'p5s':p5, 'processbars':processbars, 'qualities':qualities, 'sdate':sdate, 'edate':edate})
	
	
@login_required
def product(request, product_id):
	products = ['SecuMS', 'OmniGuard Unix', 'OmniGuard Windows', 'FOSSGuard', 'Athena']
	projectnames = ['SecuMS', 'UniTy UNIX', 'UAC for Windows(SE)', 'FOSSGuard', 'Athena Dev']
	product = products[product_id-1]
	projectname = projectnames[product_id-1]

	days = [date.today() - timedelta(x) for x in range(4, -1, -1)]
	# 전체품질 : 날짜 입력되지 않았을 경우 - 5일치, 날짜 입력 받아서 지정기간 품질 출력
	sdate = days[0].strftime("%Y-%m-%d") # 기본 시작날짜 - 5일전
	edate = days[4].strftime("%Y-%m-%d") # 기본 끝날짜 - 오늘
	if request.POST: # 입력된 날짜대로 지정 기간설정
		sdate = request.POST.get('sdate')
		edate = request.POST.get('edate')

	# 설정된 기간만큼 전체품질 현황 출력
	termset = Productquality.objects.filter(product__icontains=product, date__range=(sdate, edate)).values('manualtest', 'process', 'faulty', 'date').order_by('date')
	qualities = [{'date':term['date'].strftime("%m/%d"), 'value':term['manualtest'] + term['process'] + term['faulty']} for term in termset]
	
	# 고객사 결함현황
	allclient = Data.objects.filter(project__icontains=projectname, inputdate__date=date.today()).values('client').distinct().annotate(num=Count('client')).order_by('client')  # 전체 고객사명을 뽑음
	clientdatas = list({'client':select_cli['client'], 'num':select_cli['num']} for select_cli in allclient if select_cli['client'] != "사내")

	#등록된 프로젝트 프로세스 출력
	processbars = []
	project_set = Process.objects.filter(project__icontains=product).values('project','version', 'start', 'end', 'firststep', 'secondstep', 'thirdstep', 'file', 'is_deleted') # 프로젝트 관련정보 가져오기
	for project in project_set:
		totaldays = int(re.findall('\d+', str(project['end']-project['start']))[0])
		fstepdays = int(re.findall('\d+', str(project['firststep']-project['start']))[0])
		sstepdays = int(re.findall('\d+', str(project['secondstep']-project['firststep']))[0])
		tstepdays = int(re.findall('\d+', str(project['thirdstep']-project['secondstep']))[0])
		estepdays = int(re.findall('\d+', str(project['end']-project['thirdstep']))[0])
		currentdays = int(re.findall('\d+', str(date.today()-project['start']))[0])
		
		nowper = str(round((currentdays / totaldays) * 100))
		if int(nowper) > 100: nowper = '100'
		fdays = str(math.floor((fstepdays / totaldays) * 100))
		sdays = str(math.floor((sstepdays / totaldays) * 100))
		tdays = str(math.floor((tstepdays / totaldays) * 100))
		edays = str(math.floor((estepdays / totaldays) * 100))

		processbars.append({
			'project':project['project'],
			'version':project['version'],
			'firststep':project['firststep'],
			'secondstep':project['secondstep'],
			'thirdstep':project['thirdstep'],
			'end':project['end'],
			'fdays':fdays,
			'sdays':sdays,
			'tdays':tdays,
			'edays':edays,
			'nowper':nowper,
			'file':project['file'],
			'is_deleted':project['is_deleted'],
		})
	
	# 제품 현재 결함 수
	defectsdate = datetime.datetime.strptime(sdate, "%Y-%m-%d")
	defectedate = datetime.datetime.strptime(edate, "%Y-%m-%d")
	totalterm = int((defectedate-defectsdate).days)

	defects=[{'value':str(Data.objects.filter(project__icontains=projectname, inputdate__icontains=(defectsdate+datetime.timedelta(days=x)).strftime("%m-%d")).count()), 'date': str((defectsdate+datetime.timedelta(days=x)).strftime("%m-%d"))} for x in range(0, totalterm+1)]
	
	# 결함 수정중인 담당자 현황
	allprogrammers = Company.objects.filter(project=projectname, role='PG').distinct().values_list('name').order_by('name')
	programmers = list(Data.objects.filter(charge__in=allprogrammers, inputdate__date=date.today()).values('charge').distinct().annotate(num=Count('charge')))

	# 수정 확인중인 담당자 현황
	allmanagers = Company.objects.filter(project=projectname, role='MG').distinct().values_list('name').order_by('name')
	managers = list(Data.objects.filter(charge__in=allmanagers, inputdate__date=date.today()).values('charge').distinct().annotate(num=Count('charge')))

	# 장기간 미처리 및 미정리
	handlings = [] # 장기간 미처리 저장을 위한 리스트
	arranges = [] # 장기간 미정리 저장을 위한 리스트
	
	orderedset = Data.objects.filter(inputdate__date=date.today()).values('num', 'charge', 'startdate').order_by('startdate') # 결함을 뽑아 결함 등록날짜가 오래된 순으로 정렬
	for ordered in orderedset:
		for select_programmer in allprogrammers: # 결함의 등록날짜가 오래된 순으로 정렬된 리스트에서 프로그래머 이름이 있으면 날짜를 계산하여 저장
			if ordered['charge'] == select_programmer[0]:
				handlings.append({'id':ordered['num'], 'name':ordered['charge'], 'days':re.findall('\d+', str(date.today()-ordered['startdate']))[0]})

		for select_manager in allmanagers: # 결함의 등록날짜가 오래된 순으로 정렬된 리스트에서 담당자 이름이 있으면 날짜를 계산하여 저장
			if ordered['charge'] == select_manager[0]:
				arranges.append({'id':ordered['num'], 'name':ordered['charge'], 'days':re.findall('\d+', str(date.today()-ordered['startdate']))[0]})

Dashboard/QCEO_Django/extern/templates/extern/base.html
<!DOCTYPE html>
	<head>
		<title>QCEO</title>
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static './css/layout.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static './css/default.css' %}">
		{% block exterstyle %}
		{% endblock exterstyle %}
	</head>
	<body>
		<div id="header">
			<div class="brand">
				<a href="/dashboard">QCEO</a>
			</div>
			<p>
				<span class="motto">{{ add.motto }}</span>
			</p>
			<p>
				{% load humanize %}
				목표매출 : {{ add.goal|intcomma }} 원<br />현재매출 : {{ add.currnet|intcomma }} 원
			</p>
			<div class="user-nav">
				환영합니다, {{ user.username }}
				<a href="/logout">로그아웃</a>
			</div>
		</div>
		<div id="gnb">
			<ul>
				{% for menu in gnb_menus %}
					<li>
						<a {% if menu.url %}href="{{ menu.url }}"{% endif %}>{{ menu.name }}</a>
						<ul>
							{% for sub_menu in menu.sub_menus %}
								<li><a {% if sub_menu.url %}href="{{ sub_menu.url }}"{% endif %}>{{ sub_menu.name }}</a></li>
							{% endfor %}
						</ul>
					</li>
				{% endfor %}
			</ul>
		</div>
		<div id="container">
			{% block content %}
			{% endblock content %}
		</div>
		<div id="footer">
		</div>
	</body>
</html>

Dashboard/QCEO_Django/extern/templates/extern/dashboard.html
{% extends "extern/base.html" %}

{% block exterstyle %}
	{% load static %}
	<script type="text/javascript" src="{% static './js/fusioncharts.js' %}"></script>
	<script type="text/javascript" src="{% static './js/themes/fusioncharts.theme.fint.js' %}"></script>
	<script type="text/javascript" src="{% static './js/themes/fusioncharts.theme.ocean.js' %}"></script>
	<script>
	var today = new Date();
	FusionCharts.ready(function() {
		var Chart = new FusionCharts({
			"type": "stackedColumn2DLine",
			"renderAt": "quality",
			"width": "100%",
			"height": "300",
			"dataFormat": "json",
			"dataSource": {
				"chart": {
					/*"caption": "고객사 결함현황",*/
					/*"subCaption": "기간 3/13 ~ 3/19",*/
					"xAxisName": "LSware",
					"yAxisName": "품질(%)",
					"theme": "fint",
					"yAxisMaxValue": "100",
				},		
				"categories": [{
					"category": [
						{% for quality in qualities %}
						{
							"label": "{{ quality.date }}"
						},
						{% endfor %}
					]

				}],
				"dataset": [{
					"data": [
						{% for quality in qualities %}
						{
							"value": "{{ quality.value }}"
						},
						{% endfor %}
					]
				}, {
					"anchorBgColor": "#F5828E",
					"renderas": "Line",
					"data":  [
						{% for quality in qualities %}
						{
							"value": "{{ quality.value }}"
						},
						{% endfor %}
					]
				}],
			}

		});
		Chart.render();
	})
	FusionCharts.ready(function() {
		var Chart = new FusionCharts({
			"type": "line",
			"renderAt": "total",
			"width": "100%",
			"height": "300",
			"dataFormat": "json",
			"dataSource": {
				"chart": {
					/*"caption": "전체 결함 수",*/
					/*"subCaption": "기간 {{ sdate }} ~ {{ edate }}",*/
					"xAxisName": "LSware",
					"yAxisName": "결함 수",
					"theme": "ocean"
				},
				
				"data": 		
				[
					{% for data in datas %}
						{
							"label": "{{ data.date }}",
							"value": "{{ data.value }}"
						},
					{% endfor %}
				]
			}
		});
		Chart.render();
	});
	FusionCharts.ready(function() {
		var revenueChart = new FusionCharts({
			type: 'mscolumn2d',
			renderAt: 'eachProduct',
			width: '100%',
			height: '350',
			dataFormat: 'json',
			dataSource: {
					"chart": {
					/*"caption": "제품별 결함",*/
					/*"subCaption": "기간 "+(today.getMonth()+1)+"/"+(today.getDate()-6)+" ~ "+(today.getMonth()+1)+"/"+(today.getDate()),*/
					"xAxisName": "LSware",
					"yAxisName": "결함 수",
					"formatnumberscale": "0",
					"showvalues":"0",
					"theme": "ocean"
					},
			  
				"categories": [{
					"category": [
						{% for data in datas %}
							{
							  "label": "{{ data.date }}"
							}, 
						{% endfor %}
					]
				}],
				"dataset": [{
					"seriesname": "SecuMS",
					"data": [
						{% for p1 in p1s %}
						{
							"value": "{{p1.value}}"
						},
						{% endfor %}
					]}, {
					"seriesname": "OmniGuard Unix",
					"data": [
						{% for p2 in p2s %}
						{
							"value": "{{p2.value}}"
						},
						{% endfor %}
					]}, {
					"seriesname": "OmniGuard Windows",
					"data": [
						{% for p3 in p3s %}
						{
							"value": "{{p3.value}}"
						},
						{% endfor %}
					]}, {
					"seriesname": "FOSSGuard",
					"data": [
						{% for p4 in p4s %}
						{
							"value": "{{p4.value}}"
						},
						{% endfor %}
					]}, {
					"seriesname": "Athena",
					"data": [
						{% for p5 in p5s %}
						{
							"value": "{{p5.value}}"
						},
						{% endfor %}
					]}
			]}
		});
		revenueChart.render();
	});
	</script>
{% endblock exterstyle %}


{% block content %}

	<h1>대시보드</h1>
	
	<div class="contents">
		<h2>품질이 곧 매출이다</h2>
		<div class="search">
			<form action="" method="post" class="searchdate">
				{% csrf_token %}
				<input type="date" name="sdate" value="{{ sdate }}">
				<input type="date" name="edate" value="{{ edate }}">
				<input type="submit" value="검색">
			</form>
			<form action="/dashboard/sendmail" method="post" class="sendemail">
				{% csrf_token %}
				<input type="text" name="email">
				<input type="hidden" name="sdate" value="{{ sdate }}">
				<input type="hidden" name="edate" value="{{ edate }}">
				<input type="submit" value="이메일 보내기">
			</form>
		</div>
		<br />
		<div id="quality" class="graphs"></div>
	</div>
	
	<div class="contents">
		<h2>프로세스가 곧 품질이다</h2>
		<div class="processes">
			{% for processbar in processbars %}
				{% if processbar.is_deleted %}
				<div class="process">
					<div class="project_head">
						<span class="project_name">{{ processbar.project }}</span>
						<span class="project_version">{{ processbar.version }}</span>
					</div>
					<div class="project_body">
						<div class="steps">
							<div class="step" style="width:{{ processbar.fdays }}%">
								개발(~{{ processbar.firststep|date:"n/d" }})
							</div>
							<div class="step" style="width:{{ processbar.sdays }}%">
								품질점검(~{{ processbar.secondstep|date:"n/d" }})
							</div>
							<div class="step" style="width:{{ processbar.tdays }}%">
								패키징(~{{ processbar.thirdstep|date:"n/d" }})
							</div>
							<div class="step" style="width:{{ processbar.edays }}%">
								설치(~{{ processbar.end|date:"n/d" }})
							</div>
						</div>
						<div class="process_bar" style="width:{{ processbar.nowper }}%;background-color:#a0a0a0;">	
						</div>
					</div>
					<div class="project_tail">
						<span class="project_repoart"><a href="/report/{{ processbar.file }}">품질 점검 결과</a></span>
					</div>
				</div>	
				{% endif %}
			{% endfor %}
		</div>
	</div>

	<div class="contents">
		<h2>전체 결함</h2>
		<div id="total" class="graphs"></div>
	</div>

	<div class="contents">
		<h2>제품별 결함</h2>
		<div id="eachProduct" class="graphs"></div>
	</div>
	<ul>

	</ul>

{% endblock content %}
	

Dashboard/QCEO_Django/extern/templates/extern/email.html
<script>
	console.log(typeof({{ return }}))
	if ({{ return }} == "0")
	{
		window.alert('메일 전송 완료');
		history.back();
	}
	else {
		window.alert('메일 주소를 입력해주세요');
		history.back();
		}
</script>

<!-- {{ return }} -->

Dashboard/QCEO_Django/extern/templates/extern/login.html
<!DOCTYPE html>
	<head>
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static './css/login.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static './css/default.css' %}">
	</head>


	<body>
		<div id="login">
				<div class="logininner">
				{% if user.is_active %}
					<h2> 반갑습니다, {{user.username}} </h2>
					<a href="{% url 'extern:dashboard' %}">대시보드로 이동</a>
					<a href="{% url 'extern:logout' %}">로그아웃</a>
				{% else %}
				{% if form.errors %}
				<p>ID, PW를 확인하세요</p>
				{% endif %}
				<div class="loginForm">
					<form method="post" action="{% url 'extern:index' %}">
						{% csrf_token %}
						<h2 class="sub-title"> 로그인 </h2>
						<input class="form-control" id="{{ form.username.id_for_label }}" maxlength="15" name="{{ form.username.html_name }}" type="text" placeholder="아이디"/>
						<input class="form-control" id="{{ form.password.id_for_label }}" maxlength="120" name="{{ form.password.html_name }}" type="password" placeholder="비밀번호"/>
						<input type="submit" class="save btn btn-success" value="로그인">
						<input type="hidden" name="next" value="{% url 'extern:dashboard' %}">
					</form>
				</div>
				{% endif %}
			</div>
		</div>
	</body>
</html>

Dashboard/QCEO_Django/extern/templates/extern/logout.html
안전하게 로그아웃 되었습니다
<a href="/">홈으로가기</a>